### ISSUE TITLE
python3 support is incomplete

### ISSUE THREAD

**Issue by jlec** [tom111/tatt#21]
tatt -u sci-biology/emboss
  File "/usr/lib/python-exec/python3.4/tatt", line 172
    print "Your unmaskfile was not found, I will create it as"
                                                             ^
SyntaxError: Missing parentheses in call to 'print'

For now I will drop the support in the ebuilds, but it should be easily fixable.

**Comment by tom111** [comment]
I think I fixed all the print statements to function calls. At some point in the past python3 support was blocked since ConfigFile had no python3 version.  It seems this is fixed now, so tatt should support python3.

**Comment by jlec** [comment]
Yes, seems to work now.

**Comment by tom111** [comment]
Great.  Could you update the ebuild, please?

**Comment by jlec** [comment]
Args, I have been wrong. Still used the old ebuild

tatt -v -u sci-biology/emboss-6.6.0
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.4/tatt", line 11, in <module>
    from tatt.scriptwriter import writeusecombiscript as writeUSE
  File "/usr/lib64/python3.4/site-packages/tatt/scriptwriter.py", line 55
    os.fchmod(outfile.fileno(),0744)
                                  ^
SyntaxError: invalid token

**Comment by tom111** [comment]
I have fixed two more things in c80648a and 6e35c3af, maybe it works now?
Man, I really suck at python development. I don't even know how to test things anymore because my python path is not set correctly or something.  Sorry for the delays, this should be trivial.

**Comment by tom111** [comment]
OK, it's not done yet:
# tatt -b 552400
Bugnumber:  552400
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.3/tatt", line 135, in <module>
    bugtitle = [l for l in bugraw.splitlines() if 'Title' in l][0]
  File "/usr/lib/python-exec/python3.3/tatt", line 135, in <listcomp>
    bugtitle = [l for l in bugraw.splitlines() if 'Title' in l][0]
TypeError: Type str doesn't support the buffer API

**Comment by tom111** [comment]
In python3 the return objects of various libraries changed type to byte encoded strings where tatt wants to process utf-8 encoded strings. These should also be fixed now. Please test.

**Comment by tom111** [comment]
This is fixed in the 0.3 release that I just pushed to the tree.
Thanks!
